import { readdir, readFile, writeFile, stat } from "fs/promises";
import { join } from "path";

const contentDir = join(import.meta.dir, "../public/content");
const outFile = join(import.meta.dir, "generated-edges.ts");

const seen = new Set<string>();
const edges: { from: string; to: string; strength: number }[] = [];

// Recursively find all .md files in content directory
async function findMarkdownFiles(dir: string, prefix = ""): Promise<{ id: string; path: string }[]> {
  const entries = await readdir(dir);
  const results: { id: string; path: string }[] = [];

  for (const entry of entries) {
    const fullPath = join(dir, entry);
    const entryStat = await stat(fullPath);

    if (entryStat.isDirectory()) {
      const subResults = await findMarkdownFiles(fullPath, prefix ? `${prefix}/${entry}` : entry);
      results.push(...subResults);
    } else if (entry.endsWith(".md")) {
      const basename = entry.replace(/\.md$/, "");
      const id = prefix ? `${prefix}/${basename}` : basename;
      results.push({ id, path: fullPath });
    }
  }

  return results;
}

const files = await findMarkdownFiles(contentDir);

for (const { id, path } of files) {
  const text = await readFile(path, "utf-8");

  const match = text.match(/## (?:Related projects|See also)\n([\s\S]*?)(?=\n## |\n$|$)/);
  if (!match) continue;

  const section = match[1]!;
  const linkPattern = /\[([^\]]+)\]\(\/([^)]+)\)/g;
  let linkMatch;
  while ((linkMatch = linkPattern.exec(section)) !== null) {
    const target = linkMatch[2]!;
    const key = [id, target].sort().join("|");
    if (!seen.has(key)) {
      seen.add(key);
      const sorted = [id, target].sort();
      edges.push({ from: sorted[0]!, to: sorted[1]!, strength: 0.5 });
    }
  }
}

edges.sort((a, b) => a.from.localeCompare(b.from) || a.to.localeCompare(b.to));

const lines = edges.map((e) => `  { from: "${e.from}", to: "${e.to}", strength: ${e.strength} },`).join("\n");
const content = `// Auto-generated by gen-edges.ts - do not edit\nimport type { Edge } from "./graph";\nexport const relatedEdges: Edge[] = [\n${lines}\n];\n`;

await writeFile(outFile, content);
console.log(`wrote ${edges.length} edges to ${outFile}`);
